easy_admin:
  site_name: 'CrowdLobbying'
  entities:
    Campaign:
      class: App\Entity\Campaign
    CampaignEntry:
      class: App\Entity\CampaignEntry
    Argument:
      class: App\Entity\Argument
    WipCount:
      class: App\Entity\WipCount
    Person:
      class: App\Entity\Person
    Region:
      class: App\Entity\Region
    Party:
      class: App\Entity\Party
    PoliticianType:
      class: App\Entity\PoliticianType
    Politician:
      class: App\Entity\Politician
    PoliticianContact:
      class: App\Entity\PoliticianContact