easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@WandiColorPicker/form/fields.html.twig'

  site_name: 'CrowdLobbying'
  entities:
    Campaign:
      class: App\Entity\Campaign
      form:
        fields:
          - name
          - slug
          - start
          - end
          - arguments
          - regions
          - wipCounts
          - pages
          - politicianType
          - commissions
          - campaignTitle
          - campaignDescription
          - ogCampaignDescription
          - { property: 'ogImageFileDe', type: 'vich_image' }
          - { property: 'ogImageFileFr', type: 'vich_image' }
          - { property: 'heroBackgroundFile', type: 'vich_image' }
          - colors
          - hero
          - heroSubline
          - total
          - campaignInfoLead
          - campaignInfo
          - howItWorksStep1
          - howItWorksStep2
          - howItWorksStep3
          - howItWorksFinish
          - donorBox
          - shareTextBox
          - faqTitle
          - faqText
          - mailThanksText
          - doubleOptIn
      list:
        fields:
            - name
            - slug
            - start
            - end
            - campaignTitle
            - doubleOptIn
        actions:
          - { name: 'export' }
      show:
        fields:
          - { property: 'ogImageDe', type: 'image', base_path: '%app.path.campaign_images%' }
          - { property: 'ogImageFr', type: 'image', base_path: '%app.path.campaign_images%' }
          - { property: 'heroBackground', type: 'image', base_path: '%app.path.campaign_images%' }

    CampaignEntry:
      class: App\Entity\CampaignEntry
    Argument:
      class: App\Entity\Argument
    WipCount:
      class: App\Entity\WipCount
    Person:
      class: App\Entity\Person
    Region:
      class: App\Entity\Region
    Party:
      class: App\Entity\Party
    PoliticianType:
      class: App\Entity\PoliticianType
    Politician:
      class: App\Entity\Politician
      form:
        fields:
          - name
          - lastname
          - slug
          - since
          - lang
          - twitter
          - { property: 'imageFile', type: 'vich_image' }
          - region
          - contact
          - party
          - politicianType
          - commissions
      list:
        sort: ['lastname', 'ASC']
        fields:
          - lastname
          - name
          - { property: 'image', type: 'image', base_path: '%app.path.politician_images%' }
          - region
          - party
          - lang
          - twitter
      show:
        fields:
          - { property: 'image', type: 'image', base_path: '%app.path.politician_images%' }

    PoliticianContact:
      class: App\Entity\PoliticianContact
    Commission:
      class: App\Entity\Commission
    Color:
      class: App\Entity\Color
      list:
        fields:
          - name
          - { property: color, label: 'Color', template: 'wandi_color_picker.html.twig' }
      show:
        fields:
          - name
          - { property: color, label: 'Color', template: 'wandi_color_picker.html.twig' }
      edit:
        fields:
          - name
          - { property: color, label: 'Color', type: 'App\Form\ColorType' }
      new:
        fields:
          - name
          - { property: color, label: 'Color', type: 'App\Form\ColorType' }

    PersonArgument:
      class: App\Entity\PersonArgument
      list:
        fields:
          - id
          - createdAt
          - campaign
          - person
          - argument
      edit:
        fields:
          - argument
          - locale
          - createdAt
          - updatedAt
          - campaign
          - person
