easy_admin:
  site_name: 'CrowdLobbying'
  entities:
    Campaign:
      class: App\Entity\Campaign
      form:
        fields:
          - name
          - slug
          - start
          - end
          - arguments
          - regions
          - wipCounts
          - pages
          - politicianType

    CampaignEntry:
      class: App\Entity\CampaignEntry
    Argument:
      class: App\Entity\Argument
    WipCount:
      class: App\Entity\WipCount
    Person:
      class: App\Entity\Person
    Region:
      class: App\Entity\Region
    Party:
      class: App\Entity\Party
    PoliticianType:
      class: App\Entity\PoliticianType
    Politician:
      class: App\Entity\Politician
      form:
        fields:
          - name
          - slug
          - since
          - lang
          - twitter
          - { property: 'imageFile', type: 'vich_image' }
          - region
          - contact
          - party
          - politicianType
      list:
        fields:
          - name
          - { property: 'image', type: 'image', base_path: '%app.path.politician_images%' }
          - region
          - party
          - lang
          - twitter
      show:
        fields:
          - { property: 'image', type: 'image', base_path: '%app.path.politician_images%' }

    PoliticianContact:
      class: App\Entity\PoliticianContact
    Commission:
      class: App\Entity\Commission
