translation:
    locales: ["de", "fr"]
    edit_in_place:
        enabled: true
        config_name: app
    configs:
        app:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            remote_storage: ["php_translation.adapter.loco"]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
    webui:
        enabled: true
